(function(C){C.execute(function(){(function(e){document.createElement("header");var a=function(b){function d(a,b,d){a[d]=function(){c._replay.push(b.concat({m:d,a:[].slice.call(arguments)}))}}var c={};c._sourceName=b;c._replay=[];c.getNow=function(a,b){return b};c.when=function(){var a=[{m:"when",a:[].slice.call(arguments)}],b={};d(b,a,"run");d(b,a,"declare");d(b,a,"publish");d(b,a,"build");return b};d(c,[],"declare");d(c,[],"build");d(c,[],"publish");d(c,[],"importEvent");a._shims.push(c);return c};
a._shims=[];if(!e.$Nav)e.$Nav=a("rcx-nav");if(!e.$Nav.make)e.$Nav.make=a})(window)})})(function(){var C=window.AmazonUIPageJS||P,e=C.attributeErrors;return e?e("NavAuiShim"):C}());
/* ******** */
(function(A){A.execute(function(){function j(c){function a(){var a=Date.now();return{uid:a,suggestionsReadyForDisplay:{name:"suggestionsReadyForDisplay-"+a},suggestionsReady:{name:"suggestionsReady-"+a},suggestionsRendered:{name:"suggestionsRendered-"+a},updateSearchBox:{name:"updateSearchBox-"+a},selectionChange:{name:"selectionChange-"+a},dropdownHidden:{name:"dropdownHidden-"+a},updateSearchTerm:{name:"updateSearchTerm-"+a},suggestionClicked:{name:"suggestionClicked-"+a},suggestionsNeeded:{name:"suggestionsNeeded-"+
a},a9SuggestionsNeeded:{name:"a9-suggestionsNeeded-"+a},noSuggestions:{name:"nosuggestions-"+a},searchBoxFocusIn:{name:"searchBoxFocusIn-"+a},searchBoxFocusOut:{name:"searchBoxFocusOut-"+a},keydown:{name:"keydown-"+a},hideDropdown:{name:"hidedropdown-"+a},focusOnParent:{name:"focusOnParent-"+a},parentFocused:{name:"parentFocused-"+a},parentLostFocus:{name:"parentLostFocus-"+a},searchTermChanged:{name:"searchTermChanged-"+a},suggestionsDisplayed:{name:"suggestionsDisplayed-"+a},upArrowPressed:{name:"upArrowPressed-"+
a},downArrowPressed:{name:"downArrowPressed-"+a}}}return{globals:{issLoaded:{name:"issLoaded"},suggestionsRendered:{name:"suggestionsRendered"},initializeNavSearchBox:{name:"initializeSearchBox"}},createInstance:function(){return new a},createEvent:function(a,g){var e=g;g.hasOwnProperty("name")?e=g.name:typeof g==="string"?e=g:c.logDebug('Format of "event" parameter is not a string or an event object',g);return a+"-"+e}}}window.$Nav.when("$","nav.inline").run(function(c){window.$Nav.declare("config.blackbelt",
c("#nav-belt").length>0)});window.$Nav.when("config.blackbelt").run(function(c){c?window.$Nav.when("searchApi").run(function(a){window.$Nav.declare("sxSearchApi",a)}):window.$Nav.declare("sxSearchApi")});window.$Nav.when("$","sxSearchApi","sx.iss.DomUtils").build("NavDomApi",function(c,a,b){var g,e,h;function i(){return p?n().find('input[type="text"]'):(typeof m==="undefined"&&(m=c(g)),m)}function d(){return p?a.flyout.elem():(typeof j==="undefined"&&(j=c(s),n().after(j)),j)}function f(){return p?
a.options().parents("select"):(typeof v==="undefined"&&(v=c(e)),v)}function n(){return p?a.options().parents("form"):c(h)}function k(){var a=o(),b=d();d().is(":visible")&&!(b.html().length<1)&&b.css({left:a.offset().left,width:a.width()})}function o(){r===void 0&&(r=c("#nav-iss-attach"));return r}var p=a!==void 0;g="#twotabsearchtextbox";e="#searchDropdownBox";h="#nav-searchbar";var m,l,j,v,r,s='<div id="search-dropdown" class="search-dropdown"></div>',t=/search-alias\s*=\s*([\w-]+)/;a===void 0&&
c(window).resize(k);return{getAliasDropdown:f,getSearchBox:i,getSearchBoxId:function(){return g},getSearcchSuggestions:function(){typeof l==="undefined"&&(l=c("#srch_sggst"));return l},getKeyword:function(){var f;f=a!==void 0?a:i();return b.getKeyword(f)},setKeyword:function(b){if(a!==void 0)a.val(b);else return i().val(b)},getAliasFromDropdown:function(){var a=f().val();return(a=a&&a.match(t))?a[1]:void 0},getCategoryNameFromDropdown:function(a){var b="";a?(a=f().find('option[value$="search-alias='+
a+'"]'),b=a.length>0?c(a[0]).text():b):b=f().find("option:selected").text();return c.trim(b)},getDropdown:d,showDropdown:function(b){p?(typeof b!=="undefined"&&a.flyout.elem().html(b),a.flyout.show()):(typeof b!=="undefined"&&d().hide().html(b),b=o(),d().css({left:b.offset().left,width:b.width()}).show())},hideDropdown:function(){p?a.flyout.hide():d().hide()},getOption:function(a){if(!a)return f().find("option:selected");a=f().find('option[value$="search-alias='+a+'"]');return a.length>0?c(a[0]):
c()},getForm:n,getIssPrefixElem:function(){return c("#issprefix")},getSuggestions:function(){return c(".s-suggestion")},submitForm:function(){n().submit()},getOriginalSearchTerm:function(){return n().data("originalSearchTerm")},getOriginalAlias:function(){return n().data("originalAlias")},isSearchBoxFocused:function(){return i().get(0)===document.activeElement},activateSearchBox:function(){n().addClass("nav-active")},deactivateSearchBox:function(){n().removeClass("nav-active")},getSearchApi:function(){return a}}});
window.$Nav.build("sx.iss.TemplateEngine",function(){var c={};return function b(g,e){var h=/^[a-zA-Z0-9_-]+$/.test(g)?c[g]=c[g]||b(document.getElementById(g).innerHTML):new Function("obj","var p=[],print=function(){p.push.apply(p,arguments);};with(obj){p.push('"+g.replace(/[\r\t\n]/g," ").replace(/'(?=[^#]*#>)/g,"\t").split("'").join("\\'").split("\t").join("'").replace(/<#=(.+?)#>/g,"',$1,'").split("<#").join("');").split("#>").join("p.push('")+"');}return p.join('');");return e?h(e):h}});window.$Nav.when("$").build("sx.iss.TemplateInstaller",
function(c){function a(a,c){var e=document.createElement("script");e.setAttribute("type","text/html");e.setAttribute("id",a);e.text=c;return e}c("body");return{init:function(){var b=document.createDocumentFragment();b.appendChild(a("s-suggestion",'<div id="<#= suggestionId #>"class="s-suggestion"data-alias="<#= alias #>"data-keyword="<#= keyword #>"data-store="<#= store #>"data-isSc="<#= isSpellCorrected #>"data-isFb="<#= isFallback #>"data-type="<#= type #>"><#= bprefix #><span class="s-heavy"><#= prefix #></span><#= suffix #><# if (typeof storeHtml === "string") { #> <#= storeHtml #><# } #></div>'));
b.appendChild(a("suggestions-template",'<div id="suggestions-template"><# if (typeof suggestionTitle !== "undefined") { #><div id="suggestion-title"><#= suggestionTitle #></div><# } #><div id="suggestions"><# if (typeof suggestions !== "undefined") {for(var i=0; i < suggestions.length; i++) {var displayString = suggestions[i].display; #><#= displayString #><# }} #></div></div>'));b.appendChild(a("s-separator",'<div id="s-separator"><div class="s-separator"></div></div>'));b.appendChild(a("s-department",
'<div id="<#= suggestionId #>" class="s-suggestion s-highlight-primary"data-alias="<#= alias #>"data-keyword="<#= keyword #>"data-store="<#= store #>"data-type="<#= type #>">Shop the <#= beforePrefix #><span class="s-heavy"><#= prefix #></span><#= suffix #> store</div>'));b.appendChild(a("s-option",'<option value="<#= value #>"><#= store #></option>'));b.appendChild(a("s-minimal",'<div class="s-suggestion s-custom" data-url="<#= url #>"><#= bprefix #><span class="s-heavy"><#= prefix #></span><#= suffix #></div>'));
b.appendChild(a("s-storeText",'<span class="<#= cssClasses #>"><#= store #></span>'));b.appendChild(a("s-corpus",'<div class="s-suggestion" id="<#= suggestionId #>"data-alias="<#= alias #>"data-url="<#= url #>"data-type="<#= type #>"data-keyword="<#= keyword #>"><# if (typeof primeText !== "undefined") { #><span class="s-highlight-primary">[<#= primeText #>] </span><# } #><#= bprefix #><span class="s-heavy"><#= prefix #></span><#= suffix #></div>'));document.body.appendChild(b)}}});window.$Nav.when("sx.iss.DebugUtils",
"sx.iss.DomUtils").build("sx.iss.EventBus.instance",function(c,a){return new function(){function b(a){var b=typeof a,d="";b==="object"&&a.hasOwnProperty("name")?d=a.name:b==="string"&&(d=a);return d}var g={},e={};this.listen=function(e,i,d){var f,n="";if(a.isArray(e)){for(f=0;f<e.length;f++)n=e[f],this.listen(n,i,d),c.logDebug("Listening for: "+n);return this}n=b(e);g[n]||(g[n]=[]);g[n].push({f:i,o:d});c.logDebug("Listening for: "+n);return this};this.trigger=function(a,e){var d=b(a);c.logDebugWithTrace("Trigger: "+
d,e);var d=g[d],f;if(d){for(f=0;f<d.length;f++)d[f].f.call(d[f].o,e);return this}};this.triggerThrottledEvent=function(a,i,d){var f=b(a);c.logDebugWithTrace("Trigger (throttled): "+f,i);var n=g[f],a=e[f];if(n)return d===void 0&&(d=100),a&&(clearTimeout(a),delete e[f]),a=setTimeout(function(){var a;for(a=0;a<n.length;a++)n[a].f.call(n[a].o,i);delete e[f]},d),e[f]=a,this}}});window.$Nav.when("$","sx.iss.utils","sx.iss.Events","NavDomApi","sx.iss.DebugUtils","sx.iss.IssContext").build("sx.iss.PublicApi",
function(c,a,b,g,e,h){function i(a){g.getSearchBox().focus(a)}function d(a){a===void 0?g.getSearchBox().blur():g.getSearchBox().blur(a)}var f=/node\s*=\s*([\d]+)/,n=/bbn\s*=\s*([\d]+)/,k=/^me=([0-9A-Z]*)/,o=/^\s+/,p=/\s+/g;return{searchAlias:function(){return g.getAliasFromDropdown()},searchNode:function(){var a=g.getAliasDropdown().val().match(f);return a?a[1]:null},bbn:function(){var a=g.getAliasDropdown().val().match(n);return a?a[1]:null},merchant:function(){var a=g.getAliasDropdown().val().match(k);
return a?a[1]:null},encoding:function(){var a=g.getForm().find('input[name^="__mk_"]');if(a.length)return[a.attr("name"),a.val()]},keyword:function(a){return a!==void 0?g.setKeyword(a):g.getKeyword().replace(o,"").replace(p," ")},submit:function(a){e.logDebugWithTrace("Attaching the submit event handler to the form...");g.getForm().submit(a)},suggest:function(f){a.eventBus.listen(b.globals.suggestionsRendered,function(a){var b=[];c.each(a.suggestions,function(a,f){f.type!=="separator"&&b.push(f)});
f(a.searchTerm,b)})},onFocus:i,onBlur:d,focus:i,blur:d,keydown:function(a){var b="#"+g.getSearchBox().attr("id");g.getForm().delegate(b,"keydown",a)},setupFastLab:function(a){e.logDebugWithTrace("Fastlab",a);h.setFastlabs(a)}}});window.$Nav.when("$","NavDomApi","sx.iss.utils","sx.iss.DebugUtils","sx.iss.IssContext").build("sx.iss.Weblab",function(c,a,b,g,e){return function(a,c){function d(f,d){var c={keywords:d?d.searchTerm:void 0,alias:b.suggestionUtils.getAliasWithDeepNodeAliasBacked(a.deepNodeISS),
fastlabs:e.getTriggeredFastlabs().join("|")};e.clearTriggeredFastlabs();a.hasOwnProperty(f)&&(a[f](c),g.logDebug("Triggering: "+f+" weblabs"))}b.eventBus.listen(c.keydown,function(a){d("doCTWKeydown",a)});b.eventBus.listen(c.suggestionsRendered,function(a){d("doCTWDisplay",a)})}});window.$Nav.when("sx.iss.DebugUtils","sx.iss.DomUtils").build("sx.iss.IssContext",function(){var c,a,b=[];return{getFastlabs:function(){return a},setFastlabs:function(b){a=b},getTriggeredFastlabs:function(){return b},clearTriggeredFastlabs:function(){b=
[]},addTriggeredFastlabs:function(a){b=b.concat(a)},getConfiguration:function(){return c},setConfiguration:function(a){c=a}}});window.$Nav.when("$","sx.iss.utils","sx.iss.SuggestionTypes","NavDomApi","sx.iss.ReftagBuilder","sx.iss.DebugUtils").build("sx.iss.Reftag",function(c,a,b,g,e,h){return function(b,d,f){function c(a){return(new e).build(a,f.hasOwnProperty("shouldAddImeTag")&&f.shouldAddImeTag())}function k(a){if(a.suggestions===void 0||a.searchTerm===void 0)h.logDebug('"suggestions" or "searchTerm" is undefined',
a);else{for(var b=e.CONSTANTS.noSearchTermMatchInResults,f=a.searchTerm,a=a.suggestions,d=0;d<a.length;d++)if(f===a[d].keyword){b=e.CONSTANTS.searchTermMatchInResults;break}m(b)}}function o(){m(e.CONSTANTS.noResults)}function p(a){a.suggestion===void 0||a.searchTerm===void 0?h.logDebug('"suggestion" or "searchTerm" is undefined',a):m(c(a))}function m(a){var b=/(ref=[\-\w]+)/,f=/(dd_[a-z]{3,4})(_|$)[\w]*/,d=g.getForm(),c=d.attr("action");b.test(c)?c=f.test(c)?c.replace(f,"$1_"+a):c.replace(b,e.CONSTANTS.reftagBase+
a):(c.charAt(c.length-1)!=="/"&&(c+="/"),c+=a);d.attr("action",c)}d===void 0&&(d={});f===void 0&&(f={});a.eventBus.listen(b.selectionChange,p);a.eventBus.listen(b.suggestionsRendered,k);a.eventBus.listen(b.noSuggestions,o);return{create:c,updateReftagAfterRender:k,updateReftagAfterSelection:p,updateReftagAfterNoSuggestions:o,updateFormActionWithReftag:m}}});window.$Nav.when("$","sx.iss.SuggestionTypes","sx.iss.DataAttributes","NavDomApi","sx.iss.DebugUtils").build("sx.iss.ReftagBuilder",function(c,
a,b,g,e){function h(){function d(a){a!==void 0&&o.push(a);return this}function f(a){var a=g.getOption(a.data("alias")).val(),b=a.indexOf("=");if(b===-1)return"";var a=a.substr(b+1),b=a.indexOf("-"),f=a.substr(0,3);return b?f:f+a.charAt(b+1)}function h(c,n){var l=c.suggestion,j=c.searchTerm,v=c.previousSearchTerm;e.isDebugModeOn()&&e.logDebugWithTrace("Build reftag for search term: "+j+" pre term:"+v,l);var r=k(l),s=r.reftag;d(i.base);n&&d(i.ime);var t;if(l.data(b.fallback.name)===!0)t=i.fallback;
else if(l.data(b.spellCorrected.name)===!0)t=i.spellCorrected;t!==void 0?d(t):(l.data("type")===a.department.name&&(d(a.a9Xcat.reftag),d(l.data("alias"))),d(s));s!==a.a9.reftag&&s!==a.a9Corpus.reftag?d(0):(r=r.name,r=g.getDropdown().find('.s-suggestion[data-type="'+r+'"]').index(l)+1,d(r));l===void 0?(d(i.undefinedSugg),l=f(l),d(l)):d(v?v.length:j.length);return o.join(i.separator)}function k(b){var f=a.a9;c.each(a,function(a,d){if(b.data("type")===d.name)return f=d,!1});return f}function f(a){var a=
a.val(),b=a.indexOf("=");if(a!==""||b===-1)return"";var a=a.substr(b+1),b=a.indexOf("-")+1,f=a.substr(0,3);return b?f:f+a.charAt(b)}var o=[];return{build:h,buildFull:function(a,b){return i.reftagBase+h(a,b)}}}var i={base:"ss",fallback:"fb",spellCorrected:"sc",undefinedSugg:"dd",reftagBase:"ref=nb_sb_",noResults:"noss",searchTermMatchInResults:"noss_1",noSearchTermMatchInResults:"noss_2",ime:"ime",separator:"_"};h.CONSTANTS=i;return h});window.$Nav.when("$","NavDomApi","sx.iss.DebugUtils").build("sx.iss.suggestionUtils",
function(c,a,b){function g(a,b){return a.toLowerCase().indexOf(b.toLowerCase())}function e(a,b,f){return{bprefix:a.substr(0,b),prefix:a.substr(b,f),suffix:a.substr(b+f)}}function h(a){if(a)return a.replace(f,"")}function i(b){var f;typeof a.getAliasFromDropdown()==="undefined"&&b&&(f=b.searchAliasAccessor(c));return f}var d=/\s/,f=/#(S|E)#/g;return{getPrefixPos:g,getPrefixPosMultiWord:function(a,b){var f=a.toLowerCase().indexOf(b.toLowerCase()),e;if(f===-1)return-1;if(f===0)return 0;e=a[f-1];return e===
" "||e==="\t"||e.match(d)?f:-1},splitStringForDisplay:e,markHighlight:function(a,b){var f=g(b,a);return f>-1?(f=e(b,f,a.length),f.bprefix+"#S#"+f.prefix+"#E#"+f.suffix):b},removeHighlightMark:h,splitHighlightedString:function(a){if(a&&a.length>6){var b=a.indexOf("#S#"),f=a.indexOf("#E#");if(b>-1&&f>-1&&b+3<f)return{bprefix:h(a.substr(0,b)),prefix:h(a.substr(b+3,f-b-3)),suffix:h(a.substr(f+3))}}},getAliasWithDeepNodeAliasBacked:function(b){var f=a.getAliasFromDropdown();return f?f:i(b)},getDeepNodeAlias:i,
getDeepNodeCategoryName:function(b,f){var d;b&&(d=a.getCategoryNameFromDropdown(b)||f.searchAliasDisplayNameAccessor());return d},shouldRequestSuggestions:function(f,d){var e;if((f==="department"||f==="a9")&&d.hasOwnProperty("aliases")){var c=a.getAliasFromDropdown()||i(d.deepNodeISS);e=d.aliases==="*"||d.aliases.indexOf(c)>-1;b.logDebug("Should we request suggestions for: alias : "+c+" provider : "+f+"? "+e);return e}return!0}}});window.$Nav.when("sx.iss.TimingProvider.instance","sx.iss.EventBus.instance",
"sx.iss.suggestionUtils","sx.iss.DependenciesMet").build("sx.iss.utils",function(c,a,b){return{timingProvider:c,eventBus:a,suggestionUtils:b,now:function(){return(new Date).getTime()},escapeRegExp:function(a){return a.replace(/([.*+?\^${}()|\[\]\/\\])/g,"\\$1")}}});window.$Nav.when("$").build("sx.iss.DomUtils",function(){var c=/\+/g,a=/^\s+/;(function(){if(!Array.prototype.indexOf)Array.prototype.indexOf=function(a,c){var e=this.length>>>0,h=Number(c)||0,h=h<0?Math.ceil(h):Math.floor(h);for(h<0&&
(h+=e);h<e;h++)if(h in this&&this[h]===a)return h;return-1}})();return{isHoveredClass:"is-hovered",getKeyword:function(b){return(b=b.val())?b.replace(a,""):b},isElHoveredOver:function(a){return a.hasClass("is-hovered")},hoverOverEl:function(a){return a.addClass("is-hovered")},hoverOutEl:function(a){return a.removeClass("is-hovered")},isArray:function(a){return Object.prototype.toString.call(a)==="[object Array]"},getFormParams:function(a){for(var a=a.split("?"),g=a.length>1?a[1]:void 0,g=g?g.split("&"):
[],e=g.length,h;e-- >0;)h=g[e].split("="),g[e]={name:h[0],value:h[1].replace(c," ")};return{uri:a[0],formParams:g}},suggestionClass:".s-suggestion",hiddenInputValue:"frmDynamic",hiddenInputClass:".frmDynamic",areAnySuggestionsHoveredOver:function(a){return a.find(".is-hovered").length>0},getCursorPosition:function(a){a=a.get(0);if("selectionStart"in a)return a.selectionStart;else if(document.selection){a.focus();var c=document.selection.createRange(),e=c.text.length;c.moveStart("character",-a.value.length);
return c.text.length-e}return-1}}});window.$Nav.build("sx.iss.DebugUtils",function(){function c(a){if(a&&a.length>0)for(var a=a.substring(1).split("&"),b=0;b<a.length;b++){var d=a[b].split("=");if(d[0]==="debug"){for(var f in e)e.hasOwnProperty(f)&&(e[f]=d[1].indexOf(f)!==-1?!0:!1);break}}}function a(){return e.iss||e.isstrace}function b(){return e.isstrace}function g(b,e){a()&&window.console&&(e!==void 0?console.debug(b,e):console.debug(b))}var e={iss:!1,isstrace:!1,noiss:!1,isspolyfill:!1,isscf:!1};
c(window.location.search);return{init:c,logDebug:g,logDebugWithTrace:function(a,e){g(a,e);b()&&console.trace()},isDebugModeOn:a,isDebugModeOnWithTrace:b,isDisableISS:function(){return e.noiss},isUsingPolyFill:function(){return e.isspolyfill},isQIAEnabled:function(){return e.isscf}}});window.$Nav.build("sx.iss.ObjectUtils",function(){return{freeze:function(c){Object.freeze&&c&&Object.freeze(c)}}});window.$Nav.when("$","sx.iss.DebugUtils").run(function(c,a){a.isDisableISS()||((!c.fn.delegate||a.isUsingPolyFill())&&
c.extend(c.fn,{delegate:function(b,g,e){return this.bind(g,function(g){var i=c(g.target);if(i.is(b)||i.parents(b).length>0)return a.logDebug("delegate ",{selector:b,target:i,event:g}),e.apply(i,arguments)})}}),window.$Nav.declare("sx.iss.DependenciesMet"))});window.$Nav.when("sx.iss.DepartmentDataFormatter").build("sx.iss.DepartmentData",function(c){var a=[["instant-video","Amazon Instant Video",["Amazon","Instant","Video","movies","rentals"]],["appliances","Appliances",["Appliances"]],["mobile-apps",
"Apps for Android",["Apps","Android","mobile"]],["arts-crafts","Arts, Crafts & Sewing",["arts","crafts","sewing"]],["automotive","Automotive",["automotive","cars"]],["baby-products","Baby Products",["baby","products"]],["beauty","Beauty",["beauty","makeup","hair"]],["stripbooks","Books",["books","textbooks","rentals"]],["mobile","Cell Phones & Accessories","cell,phones,mobile,cases,iphone,galaxy,nexus".split(",")],["collectibles","Collectibles & Fine Art",["collectibles","fine","art"]],["computers",
"Computers",["computers","pc","laptop","desktop"]],["electronics","Electronics",["electronics"]],["financial","Credit Cards",["credit","cards"]],["gift-cards","Gift Cards Store",["gift","cards"]],["grocery","Grocery & Gourmet Food",["grocery","gourmet","food"]],["hpc","Health & Personal Care",["health","personal","care"]],["garden","Home & Kitchen",["home","kitchen","furniture","art"]],["industrial","Industrial & Scientific",["Industrial","Scientific"]],["digital-text","Kindle Store",["kindle","store",
"ebooks"]],["magazines","Magazine Subscriptions",["magazines","subscriptions"]],["movies-tv","Movies & TV","movies,tv,dvds,vhs,video,blu ray,bluray,blu-ray".split(",")],["digital-music","MP3 Music",["mp3","music"]],["popular","Music",["music","cds","autorip","vinyl"]],["mi","Musical Instruments",["musical","instruments","guitars","dj"]],["office-products","Office Products",["office","products","school","toner"]],["lawngarden","Patio, Lawn & Garden",["patio","lawn","garden"]],["pets","Pet Supplies",
"pet,supplies,dogs,cats,birds,fish".split(",")],["software","Software",["software"]],["sporting","Sporting & Outdoors",["sporting","outdoors","sports"]],["tools","Tools & Home Improvement",["tools","home","improvement"]],["toys-and-games","Toys & Games",["toys","games"]],["videogames","Video Games","video,games,xbox,ps3,ps4,wii,playstation".split(",")],["wine","Wine",["wine"]],["pantry","Prime Pantry",["prime","pantry"]]],b=[["fashion","Clothing, Shoes & Jewelry","clothing,clothes,luggage,hats,shirts,jacket,wallets,sunglasses,jewelry,shoes,handbags,sandals,boots,watches".split(",")],
["fashion-mens","Men's Clothing, Shoes & Jewelry","mens,clothing,clothes,shoes,jewelry,mens clothing,mens shoes,mens jewelry,watches,mens watches".split(",")],["fashion-womens","Women's Clothing, Shoes & Jewelry","womens,clothing,clothes,shoes,jewelry,womens clothing,womens shoes,womens jewelry,watches,womens watches".split(",")],["fashion-baby","Baby Clothing, Shoes & Jewelry","baby,clothing,clothes,shoes,jewelry,baby clothing,baby shoes,baby jewelry".split(",")],["fashion-boys","Boys Clothing, Shoes & Jewelry",
"boys,clothing,clothes,shoes,jewelry,boys clothing,boys shoes,boys jewelry".split(",")],["fashion-girls","Girls' Clothing, Shoes & Jewelry","girls,clothing,clothes,shoes,jewelry,girls clothing,girls shoes,girls jewelry".split(",")]],g=[["jewelry","Jewelry",["jewelry"]],["shoes","Shoes",["shoes","handbags","sandals","boots"]],["apparel","Clothing & Accessories","clothing,clothes,hats,shirts,jacket,wallets,sunglasses".split(",")]];return{getData:function(e){var h=a,e=typeof e!=="undefined"&&e.hasOwnProperty("isWayfindingEnabled")&&
e.isWayfindingEnabled===1?b:g,h=h.concat(e);return c.format(h)}}});window.$Nav.build("sx.iss.DepartmentDataFormatter",function(){return{format:function(c){for(var a=[],b=0;b<c.length;b++){var g=c[b];a.push({id:g[0],alias:g[0],keyword:"",type:"department",store:g[1],name:"",triggerWords:g[2],sn:!1})}return a}}});window.$Nav.when("sx.iss.ObjectUtils").build("sx.iss.SuggestionTypes",function(c){var a={a9:{name:"a9",reftag:"i",templateId:"s-suggestion"},a9Xcat:{name:"a9-xcat",reftag:"c",templateId:"s-suggestion"},
a9XOnly:{name:"a9-xcat-only",reftag:"xo",source:"xo",templateId:"s-suggestion"},a9Corpus:{name:"a9-corpus",reftag:"cp",reftagTemplate:"REF_TAG",templateId:"s-corpus"},department:{name:"department",reftag:"deptiss",templateId:"s-department"}};c.freeze(a);return a});window.$Nav.when("sx.iss.ObjectUtils").build("sx.iss.InfoTypes",function(c){var a={actor:"actor",author:"author",director:"director",seasonTitle:"season_title",title:"title"};c.freeze(a);return a});window.$Nav.build("sx.iss.DataAttributes",
function(){return{fallback:{name:"isfb"},spellCorrected:{name:"issc"}}});window.$Nav.build("sx.iss.TimingEvents",function(){return{latency:{group:"Latency",events:{timeToDisplay:"timeToDisplay"}}}});window.$Nav.when("sx.iss.DebugUtils").build("sx.iss.Events",j);window.$Nav.when("sx.iss.ObjectUtils").build("sx.iss.Platform",function(c){var a={name:"desktop",cid:"amazon-search-ui",callback:"String",needExtraParams:!0};c.freeze(a);return a});window.$Nav.when("$").build("sx.iss.TimingProvider.instance",
function(c){return new function(){var a={};this.startTimer=function(b,c){a[b]||(a[b]={});a[b][c]={start:+new Date}};this.stopTimer=function(b,c){var e=a[b]&&a[b][c];if(!e)return-1;e.end=+new Date;return e.end-e.start};this.getTimings=function(b){return a[b]};this.getTimingStats=function(b){var g={name:b},e=0,h=0,i=void 0,d=void 0,f=0,n=0,k=[],o=0,j=0;if(a[b]){c.each(a[b],function(a,b){if(b.start&&b.end){n=b.end-b.start;k.push(n);f++;h+=n;if(!i||n<i)i=n;if(!d||n>d)d=n}});k.sort();g.n=f;g.avg=h/f;g.min=
i;g.max=d;g.med=f===1?k[0]:f%2?(k[Math.floor(f/2)]+k[Math.ceil(f/2)])/2:k[f/2];for(e=0;e<f;e++)o=k[e]-g.avg,o*=o,j+=o;g.stddev=Math.sqrt(j/f);return g}};this.getTimingWithDisplayLatency=function(b,c){var e=a[b]&&a[b][c];return!e?-1:e.end-e.start+100}}});window.$Nav.when("$","sx.iss.utils","NavDomApi","sx.iss.Events","sx.iss.SuggestionTypes","sx.iss.A9SuggestionQueryConstructors","sx.iss.A9SuggestionResultsProcessors","sx.iss.DebugUtils").build("sx.iss.A9SuggestionProvider",function(c,a,b,g,e,h,i,
d){var f="a9",n=e.a9;return function(b,o,j){function m(b,h){var i=++q,n,m;v=document.getElementsByTagName("head").item(0);r="JscriptId"+i;s=document.createElement("script");s.setAttribute("type","text/javascript");s.setAttribute("charset","utf-8");s.setAttribute("src",h);s.setAttribute("id",r);s.onload=s.onreadystatechange=function(){if(!(n||this.readyState!==void 0&&this.readyState!=="loaded"&&this.readyState!=="complete")){n=!0;if(completion!=="undefined"){var h=l(),k=!h||c.inArray(h,C)===-1?e.a9:
e.a9Corpus;m=u.getResultsProcessor(k.name).processResults(b,h,completion)}this.onload=this.onreadystatechange=null;try{v.removeChild(s)}catch(t){d.logDebug(t)}a.timingProvider.stopTimer(f,i);h={searchTerm:b,suggestionSets:m};k=g.createEvent(f,j.suggestionsReady);a.eventBus.trigger(k,h)}};a.timingProvider.startTimer(f,i);v.appendChild(s)}function l(){var k;var b="aps",b=[],b=o.aliases;return k=(b=o.implicitAlias?[o.implicitAlias]:typeof b==="string"?b.split(","):b)&&b.length===1?b[0]:a.suggestionUtils.getAliasWithDeepNodeAliasBacked(o.deepNodeISS),
b=k}var q=0,v,r,s,t=new h(o),u=new i(o),C=o.issCorpus||[];a.eventBus.listen(j.a9SuggestionsNeeded,function(b){if(a.suggestionUtils.shouldRequestSuggestions(f,o))if(!b||!b.length){var b={searchTerm:b,suggestions:[]},d=g.createEvent(f,j.suggestionsReady);a.eventBus.trigger(d,b)}else{var d=l(),h=!d||c.inArray(d,C)===-1?e.a9:e.a9Corpus;(d=t.getUrlConstructor(h.name).constructUrl(b,d))&&m.call(this,b,d)}},this);return{getName:function(){return f},processResults:u.getResultsProcessor(n.name).processResults}}});
window.$Nav.when("$","sx.iss.utils","NavDomApi","sx.iss.DomUtils","sx.iss.SuggestionTypes","sx.iss.Platform","sx.iss.DebugUtils","sx.iss.IssContext").build("sx.iss.A9SuggestionQueryConstructors",function(c,a,b,g,e,h,i,d){return function(f){function n(a){return{constructUrl:function(){i.logDebugWithTrace("Invalid suggestion type provided: "+a+" when asking for query constructors");return""}}}function k(a){var f=g.getCursorPosition(b.getSearchBox());return f>-1?{q:encodeURIComponent(c.trim(a.substring(0,
f))),qs:encodeURIComponent(a.substring(f))}:{q:encodeURIComponent(a)}}function o(a){var b="?";c.each(a,function(a,f){b+=a+"="+f+"&"});return b}function j(b){var d={xcat:f.xcat,cf:f.cf,noCacheIE:a.now()};if(f.fb!==void 0)d.fb=f.fb;if(f.np!==void 0)d.np=f.np;if(f.issPrimeEligible&&c.inArray(b,f.issPrimeEligible)!==-1)d.pf=1,d.fb=0;d.sc=1;return d}var m=f.protocol||window.parent.document.location.protocol||"http:";m==="file:"&&(m="http:");var l={};l[e.a9.name]=new function(){var a=m+"//"+f.src,b={method:"completion",
mkt:f.mkt,client:h.cid,x:h.callback};return{constructUrl:function(f,e){var g=c.extend({},b,{"search-alias":e},k(f));h.needExtraParams&&c.extend(g,j(e));d.getFastlabs()&&c.extend(g,{w:d.getFastlabs()});return a+o(g)}}};l[e.a9Corpus.name]=new function(){var a=m+"//"+f.src.replace("/search","/v2.0"),b={"num-corpus":10,"num-query":5,client:h.cid,m:f.obfMkt,fb:1,xcat:1,method:"completion",cf:0,sc:1,conf:1,x:h.callback};return{constructUrl:function(f,d){var e=c.extend({},b,{"search-alias":d},k(f));return a+
o(e)}}};return{getUrlConstructor:function(a){return l.hasOwnProperty(a)?l[a]:new n(a)}}}});window.$Nav.when("$","sx.iss.utils","NavDomApi","sx.iss.DomUtils","sx.iss.SuggestionTypes","sx.iss.InfoTypes","sx.iss.DebugUtils","sx.iss.IssContext").build("sx.iss.A9SuggestionResultsProcessors",function(c,a,b,g,e,h,i,d){var f;f="aps";return function(c){function k(a){return{processResults:function(){i.logDebugWithTrace("Invalid suggestion type provided: "+a+" when asking for result processing");return""}}}
function o(b,f,d,e,c,g,h){var i=a.suggestionUtils.getPrefixPos(e,d),n;c||i===-1?(d=e,i=n=""):(n=a.suggestionUtils.splitStringForDisplay(e,i,d.length),d=n.bprefix,i=n.prefix,n=n.suffix);return{type:g,isSpellCorrected:c,bprefix:d,prefix:i,suffix:n,keyword:e,isFirst:h===0,alias:b,store:f,isDeepNode:b!==void 0&&f!==void 0}}function j(a,b,f,d){a.store=b.name;a.alias=b.alias;a.type=f?e.a9XOnly.name:e.a9Xcat.name;a.isFallback=d;return a}function m(a,d,c){d.isFirst=!1;if(c)d.type=e.a9XOnly.name;else if(d.type=
e.a9Xcat.name,c=b.getAliasFromDropdown(),c!==f)d.store=b.getCategoryNameFromDropdown(c),d.alias=c,a.push(l(d));d.store=b.getCategoryNameFromDropdown(f);d.alias=f;a.push(l(d))}function l(a,f){var d={type:a.type,bprefix:a.bprefix,prefix:a.prefix,suffix:a.suffix,keyword:a.keyword,alias:a.alias||f,isSpellCorrected:a.isSpellCorrected,isFallback:a.isFallback,isDeepNode:a.isDeepNode},g;if(d.type===e.a9Xcat.name||d.type===e.a9XOnly.name||d.isDeepNode===!0){if(a.isFirst||!c.noXcats)a.store?g=a.store:a.isFirst&&
(g=b.getCategoryNameFromDropdown())}else g=void 0;d.store=g;g=d.alias;var h="/s?k="+encodeURIComponent(a.keyword);typeof g!==void 0&&(h+="&i="+encodeURIComponent(g));d.url=h;return d}var q={};q[e.a9.name]=new function(){var b=e.a9.name;return{processResults:function(f,h,i){var k=i[1],C=i[2]||[],i=i[3]||[],w=0,q=[],D=[],L,B,F;F=!1;for(var E=0;E<C.length;E++){var x=C[E];if(x.hasOwnProperty("source"))for(var x=x.source,z=0;z<x.length;z++)if(x[z]==="fb"){F=!0;break}}E=!1;for(x=0;x<C.length;x++)if(z=C[x],
z.hasOwnProperty("nodes")&&z.nodes.length>0){E=!0;break}if(x=c.hasOwnProperty("cf"))if(x=c.cf){x=!1;for(z=0;z<C.length;z++){var y=C[z];if(y.hasOwnProperty("nodes")&&y.nodes.length>0&&y.hasOwnProperty("source")&&g.isArray(y.source)&&y.source[0]==="xo"){x=!0;break}}}c.deepNodeISS&&(L=a.suggestionUtils.getDeepNodeAlias(c.deepNodeISS),B=a.suggestionUtils.getDeepNodeCategoryName(L,c.deepNodeISS));z=typeof L!=="undefined";for(y=0;y<k.length;y++){var K=o(L,B,f,k[y],C&&C[y]&&C[y].sc==="1",b,y);F||q.push(l(K,
h));if(!c.noXcats&&E){!F&&y===0&&(z||m(D,K,x),(x||!z)&&q.shift());for(var I=C[y],A=I&&I.source&&I.source[0]==="fb",I=I.nodes||[],G=0;G<I.length&&w<4;G++)K=j(K,I[G],x,A),D.push(l(K,h)),w++}}f={};f[e.a9.name]=q;f[x?e.a9XOnly.name:e.a9Xcat.name]=D;i.length>0&&i[0].hasOwnProperty("t")&&d.addTriggeredFastlabs(i[0].t);return f}}};q[e.a9Corpus.name]=new function(){function b(f,d,g,h,i,m,k){d=o(d,void 0,g,h,i,e.a9Corpus.name,k);if(g=a.suggestionUtils.splitHighlightedString(h))d.bprefix=g.bprefix,d.prefix=
g.prefix,d.suffix=g.suffix;h=a.suggestionUtils.removeHighlightMark(h);d.keyword=h;d.text=h;d.url="/dp/"+f+"/"+e.a9Corpus.reftagTemplate+"?ie=utf8&keywords="+encodeURIComponent(h);if(m)d.primeText=c.primeText;return d}function f(a){for(var b=[],d=0;d<a.length;d++)b.push(a[d].field);return b}return{processResults:function(d,g,i){var k=[],w=[],i=i.suggs,q,D;if(i.length===0)return[];for(var L=i.length,B=0;B<i.length;B++)if(i[B].hasOwnProperty("corpus")){var F=f(i[B].source);if((F.indexOf(h.title)>=0||
F.indexOf(h.seasonTitle)>=0)&&i[B].corpus.length>1)i[B].alwaysShowDirector=!0}else{L=B;break}c.deepNodeISS&&(q=a.suggestionUtils.getDeepNodeAlias(c.deepNodeISS),D=a.suggestionUtils.getDeepNodeCategoryName(q,c.deepNodeISS));for(B=L;B<i.length&&w.length<4;B++){var E=i[B];if(F=E.xcats)for(var x=F.hasOwnProperty("sc")&&F.sc!==0,z=E.hasOwnProperty("fb")&&E.fb!==0,y=0;y<F.length&&w.length<4;y++){var K=w,I=q,A=F[y],G=z,N=B-L+y,H=o(I,D,d,E.sugg,x,e.a9Xcat.name,N),H=j(H,A,!1,G);N===0&&!G&&typeof I==="undefined"?
m(K,H):K.push(l(H))}}q=10-w.length;for(B=0;B<L&&k.length<q;B++){E=i[B];D=E.corpus;F=f(E.source);for(y=0;y<D.length&&k.length<10;y++){x=D[y];z=E;K=x.asin_info;I=F;A=d;G="";for(N=0;N<K.length;N++){var M=K[N],H=M.type,M=M.value;if(H===h.title||H===h.seasonTitle)G+=a.suggestionUtils.markHighlight(A,M[0]);z.alwaysShowDirector&&H===h.director?G+=c.directedByText.replace("{director}",M[0]):I.indexOf(H)>=0&&M.indexOf(z.sugg)>=0&&(M=a.suggestionUtils.markHighlight(A,z.sugg),H===h.actor?G+=c.starringText.replace("{actor}",
M):H===h.director&&(G+=c.directedByText.replace("{director}",M)))}z=G;K=x.hasOwnProperty("is_prime")&&x.is_prime===1;k.push(b(x.asin,g,d,z,!1,K,y))}}d={};d[e.a9Corpus.name]=k;d[e.a9Xcat.name]=w;return d}}};return{getResultsProcessor:function(a){return q.hasOwnProperty(a)?q[a]:new k(a)}}}});window.$Nav.when("$","sx.iss.utils","sx.iss.DepartmentData","NavDomApi","sx.iss.Events").build("sx.iss.DepartmentSuggestionProvider",function(c,a,b,g,e){function h(h,k){function o(o){if(a.suggestionUtils.shouldRequestSuggestions(i,
h)){var m={searchTerm:o,suggestionSets:{}},l=[],j=RegExp("\\b"+a.escapeRegExp(o)+"(.*)","i");if(o.length>=d&&g.getKeyword().length===o.length){var v,r,s,t;c.each(b.getData(h),function(b,d){t=s=r="";if(j.test(d.triggerWords)||j.test(d.store)){d.position=l.length===0?0:l.length+1;var e=a.suggestionUtils.getPrefixPos(d.store,o);e===-1?t=d.store:(v=a.suggestionUtils.splitStringForDisplay(d.store,e,o.length),r=v.bprefix,s=v.prefix,t=v.suffix);d.beforePrefix=r;d.prefix=s;d.suffix=t;l.push(d);if((e=window.ue)&&
e.count){var c=i+d.alias.replace("-","");e.count(c,e.count(c)+1)}}if(l.length===f)return!1})}m.suggestionSets[i]=l;var u=e.createEvent(i,k.suggestionsReady);a.eventBus.trigger(u,m)}}(function(){var b=e.createEvent(i,k.suggestionsNeeded);a.eventBus.listen(b,o)})()}var i="department",d=3,f=3;h.prototype.getName=function(){return i};return h});window.$Nav.when("sx.iss.utils").build("sx.iss.HelpSuggestionProvider",function(c){var a=[{type:"help",pat:/^return/i,text:"Looking for help with returns? Try this.",
url:""},{type:"help",pat:/^track/i,text:"Looking for help with tracking? Try this.",url:""},{type:"help",pat:/^gift[\s*]w/i,text:"Looking for help with gift wrapping? Try this.",url:""},{type:"help",pat:/^canc/i,text:"Looking for help with order cancellation? Try this.",url:""},{type:"help",pat:/^refu[\s*]/i,text:"Looking for help with refund? Try this.",url:""},{type:"help",pat:/^passw[\s*]/i,text:"Looking for help with passwords? Try this.",url:""},{type:"help",pat:/^log(ging\s*)?o/i,text:"Looking for help with logging out? Try this.",
url:""}];return function(){this.getName=function(){return"help"};c.eventBus.listen("help-suggestionsNeeded",function(b){var g,e=[];for(g=0;g<a.length;g++)b.match(a[g].pat)&&e.push(a[g]);c.eventBus.trigger("help-suggestionsReady",{searchTerm:b,suggestions:e})},this)}});window.$Nav.when("$","sx.iss.utils").build("sx.iss.RecentSearchSuggestionProvider",function(c,a){return function(b){var g=/[^\w]/;this.getName=function(){return"recent"};var e=j.createEvent("recent",b.suggestionsNeeded);a.eventBus.listen(e,
function(e){var i=[];if(window.sx&&window.sx.searchsuggest&&window.sx.searchsuggest.searchedText){var d=window.sx.searchsuggest.searchedText,f={},n,k,o,p,m,l,q=!e||!g.test(e)?e:c("<div></div>").text(e).html();for(p=0;p<d.length;p++)if(k=d[p].keywords,n=!k||!g.test(k)?k:c("<div></div>").html(k).text(),o=a.suggestionUtils.getPrefixPosMultiWord(k,q),!f[k]&&a.suggestionUtils.getPrefixPosMultiWord(n,e)!==-1)o===-1?(o=k,l=m=""):(m=a.suggestionUtils.splitStringForDisplay(k,o,q.length),o=m.bprefix,l=m.prefix,
m=m.suffix),i.push({type:"recent",spellCor:!1,bprefix:o,prefix:l,suffix:m,keyword:n,originalKeywords:k,deleteUrl:d[p].deleteUrl}),f[k]=1}d=j.createEvent("recent",b.suggestionsReady);a.eventBus.trigger(d,{searchTerm:e,suggestions:i})},this)}});window.$Nav.when("$","sx.iss.utils","sx.iss.TemplateEngine").build("sx.iss.SuggestionDisplayProvider",function(c,a,b){return function(a,e,h){var i,d;this.getDisplay=function(a){if(i(a))return c.extend(a,h),d(a)};i=typeof a==="string"?function(b){return b.type===
a}:a;d=b(e)}});window.$Nav.when("$","sx.iss.utils").build("sx.iss.SuggestionHighlightingProvider",function(c,a){return function(b){function g(a){a=a.currentTarget.id;f&&f.removeClass(f.attr("data-selected-class"));f=c("#"+a);d=parseInt(a.substr(6));f.addClass(f.attr("data-selected-class"))}function e(a){a=a.currentTarget.id;f&&f.attr("id")===a&&(f.removeClass(f.attr("data-selected-class")),f=void 0,d=-1)}var h=this,i,d=-1,f;a.eventBus.listen(b.suggestionsDisplayed,function(a){var b;i=a;d=-1;f=void 0;
for(a=0;a<i.suggestions.length;a++)b=c("#"+i.suggestions[a].suggestionId),b.bind("mouseover",h,g).bind("mouseout",h,e)},this).listen(b.upArrowPressed,function(){i&&(f&&f.removeClass(f.attr("data-selected-class")),d--,d===-1?a.eventBus.trigger(b.suggestionSelected,{keyword:i.searchTerm}):(d===-2&&(d=i.suggestions.length-1),f=c("#issDiv"+d),f.addClass(f.attr("data-selected-class")),a.eventBus.trigger(b.suggestionSelected,i.suggestions[d])))},this).listen(b.downArrowPressed,function(){i&&(f&&f.removeClass(f.attr("data-selected-class")),
d++,d===i.suggestions.length?(d=-1,a.eventBus.trigger(b.suggestionSelected,{keyword:i.searchTerm})):(f=c("#issDiv"+d),f.addClass(f.attr("data-selected-class")),a.eventBus.trigger(b.suggestionSelected,i.suggestions[d])))},this)}});window.$Nav.when("sx.iss.utils","sx.iss.SuggestionTypes","sx.iss.TemplateEngine").build("sx.iss.IssDisplayProvider",function(c,a,b){return function(g,e,h,i,d){function f(a){c.eventBus.trigger(i.suggestionsNeeded,a)}function n(b){var f=e.sequence(b),b=b.searchTerm,g=j++;c.timingProvider.startTimer("IssDisplayProvider",
g);if(f.length===0)c.eventBus.trigger(i.noSuggestions,b);else{for(var n=h,r=0,s=0;s<f.length;s++){var t=f[s];if(t.type!=="separator")t.suggestionId="issDiv"+r,r++;var u=t,C="";C+=t.isDeepNode===!0?"s-highlight-secondary":"s-highlight-primary";u.cssClasses=C;for(var w,u=0;u<n.length;u++)if(w=n[u],w=k(w,t),w=w.getDisplay(t))break;t.display=w}n=f&&f.length>0&&f[0].type===a.a9Corpus.name&&d.hasOwnProperty("issCorpusSugText");n=o({suggestions:f,suggestionTitle:n?d.issCorpusSugText:d.hasOwnProperty("sugText")?
d.sugText:""});c.timingProvider.stopTimer("IssDisplayProvider",g);c.eventBus.trigger(i.suggestionsReadyForDisplay,{searchTerm:b,display:n,suggestions:f})}}function k(a,b){var f=a;if(a.hasOwnProperty("provider")&&a.hasOwnProperty("partials")){for(f=0;f<a.partials.length;f++){var d=a.partials[f],e=d.provider.getDisplay(b);d.hasOwnProperty("formatter")&&(e=d.formatter.string.replace(d.formatter.toReplace,e));b[d.key]=e}f=a.provider}return f}var o=b(g),j=0;(function(){c.eventBus.listen(i.suggestionsReady,
n,this);c.eventBus.listen(["parentFocused","searchTermChanged"],f,this)})();return{processPartials:k}}});window.$Nav.when("sx.iss.utils","sx.iss.Events").build("sx.iss.ArraySuggestionProvider",function(c,a){return function(b,g){function e(b){for(var e=[],b=b.toLowerCase(),j=0;j<i.length;j++){var m=i[j];if(m.toLowerCase().indexOf(b)!==-1&&e.length<f){var m={term:m,searchTerm:b,url:d[j]},l=c.suggestionUtils.getPrefixPos(m.term,m.searchTerm),l=c.suggestionUtils.splitStringForDisplay(m.term,l,m.searchTerm.length),
m={type:n,bprefix:l.bprefix,prefix:l.prefix,suffix:l.suffix,keyword:m.searchTerm,url:m.url,isExactMatch:m.term===m.searchTerm};e.push(m)}}b={searchTerm:b,suggestionSets:{array:e}};e=a.createEvent(h,g.suggestionsReady);c.eventBus.trigger(e,b)}var h="array",i=b[0],d=b[1],f=10,n="array";(function(){var b=a.createEvent(h,g.suggestionsNeeded);c.eventBus.listen(b,e,this)})();return{name:h}}});window.$Nav.when("$","sx.iss.utils","sx.iss.TimingEvents","sx.iss.TemplateEngine","NavDomApi","sx.iss.SuggestionTypes",
"sx.iss.ReftagBuilder").build("sx.iss.DesktopSearchBoxEventHandler",function(c,a,b,g,e,h,i){var d=e.getSearchApi();return function(f){function n(){q=!0;r||(r=!0)}function k(){v=!0}function o(){e.activateSearchBox()}function j(){e.deactivateSearchBox()}a.eventBus.listen(f.selectionChange,function(f){m===void 0&&(m=e.getAliasFromDropdown());if(f.isScrollIntoSearchBox===!0)f=f.previousSearchTerm,e.getIssPrefixElem().remove(),l.val(f),e.getAliasDropdown().val("search-alias="+m).trigger("change");else{var d=
a.timingProvider.getTimingWithDisplayLatency(b.latency.group,b.latency.events.timeToDisplay),d=e.getKeyword()+","+e.getOriginalAlias()+","+d,h=e.getIssPrefixElem();h.length>0?h.attr("value",d):(d=c('<input type="hidden"/>').attr("id","issprefix").attr("name","sprefix").attr("value",d),e.getForm().append(d));var f=f.suggestion,i=f.attr("data-alias"),h=e.getOption(i),d=e.getAliasDropdown(),i="search-alias="+i;h.length===0?(h=f.data("store"),h!==void 0&&h!==""&&d.append(g("s-option",{value:i,store:h}))):
i=h.val();d.val(i).trigger("change");e.setKeyword(f.attr("data-keyword"))}});a.eventBus.listen(f.hideDropdown,function(b){q===!0&&v===!0&&(b.keyCode===27||b.keyCode===13)?(q=v=!1,a.eventBus.triggerThrottledEvent(f.suggestionsNeeded,e.getKeyword())):(e.hideDropdown(),e.getIssPrefixElem().remove(),m=void 0)});a.eventBus.listen(f.suggestionClicked,function(b){var d=b.suggestion;a.eventBus.trigger(f.updateSearchBox,d);b={suggestion:d,searchTerm:e.getKeyword(),previousSearchTerm:b.previousSearchTerm};
a.eventBus.trigger(f.selectionChange,b);e.hideDropdown();d.attr("data-type")===h.a9Corpus.name?(d=d.attr("data-url"),window.location=d.replace(h.a9Corpus.reftagTemplate,(new i).buildFull(b,r))):e.submitForm()});a.eventBus.listen(f.noSuggestions,function(){e.hideDropdown()});a.eventBus.listen(f.suggestionsNeeded,function(){m=e.getAliasFromDropdown()});d===void 0&&(a.eventBus.listen(f.searchBoxFocusIn,o),a.eventBus.listen(f.searchBoxFocusOut,j));d!==void 0?(d.on("compositionstart",n),d.on("compositionend",
k)):c("#navbar").delegate("#twotabsearchtextbox","compositionstart",n).delegate("#twotabsearchtextbox","compositionend",k);var m,l=e.getSearchBox(),q=!1,v=!1,r=!1;return{getWasCompositionUsed:function(){return r}}}});window.$Nav.when("sx.iss.utils").build("sx.iss.A9SearchSuggestionEventHandler",function(c){return function(a){var b;this.getDelegateReqs=function(){return{selectors:".a9_suggestion,.suggestion_with_query_builder",events:"click"}};this.handleEvent=function(g){var e=g.target||g.srcElement,
g=parseInt(g.currentTarget.id.substr(6),10);e.className&&e.className.indexOf("suggest_builder")!=-1?c.eventBus.trigger(a.updateSearchTerm,b.suggestions[g].keyword):c.eventBus.trigger(a.suggestionClicked,{suggestion:b.suggestions[g]})};c.eventBus.listen(a.suggestionsDisplayed,function(a){b=a},this)}});window.$Nav.when("sx.iss.utils").build("sx.iss.RecentSearchSuggestionEventHandler",function(c){return function(a){function b(b){var e,d,f,g;e=location.protocol+"//"+location.host+b.deleteUrl;d=window.sx.searchsuggest.searchedText;
for(f=0;f<d.length;f++)if(d[f].keywords===b.originalKeywords){g=f;break}g!==-1&&d.splice(g,1);c.eventBus.trigger(a.focusOnParent);var k;window.XMLHttpRequest?k=new XMLHttpRequest:window.ActiveXObject&&(k=new ActiveXObject("Microsoft.XMLHTTP"));if(k&&e)try{k.open("GET",e,!0),k.send(null)}catch(o){}}var g=this,e;this.getDelegateReqs=function(){return{selectors:".recent_search_suggestion",events:"click"}};this.handleEvent=function(h){var i=h.target||h.srcElement,h=parseInt(h.currentTarget.id.substr(6),
10);i.className&&i.className.indexOf("iss_sh_delete")!=-1?b.call(g,e.suggestions[h]):c.eventBus.trigger(a.suggestionClicked,{suggestion:e.suggestions[h]})};c.eventBus.listen(a.suggestionsDisplayed,function(a){e=a},this)}});window.$Nav.when("$","sx.iss.utils","sx.iss.DomUtils","sx.iss.TimingEvents","sx.iss.TemplateEngine","sx.iss.DebugUtils").build("sx.iss.SearchBoxEventHandler",function(c,a,b,g,e,h){var i=[37,38,39,40,91,92,93,192];return function(d,f,e){function g(f){a.eventBus.trigger(e.keydown);
var d=f.keyCode,i=d===40,m=d===38,k;if(r.find("#suggestions-template").is(":visible")){if(i||m){t===void 0&&(t=b.getKeyword(s));var l=r.find(".s-suggestion"),o=l.index(c(".s-selected"));(m=o===0&&m||o+1===l.length&&i)?r.find(".s-suggestion").removeClass("s-selected"):(h.logDebug("highlighting suggestion"),k=r.find(".s-suggestion"),l=k.index(q()),o=k.length,i?(i=-1,l===-1||l===o-1?i=0:l<o&&(i=l+1)):(i=-1,l<1?i=o-1:l<=o&&(i=l-1)),k.eq(l).removeClass("s-selected"),i=k.eq(i),i.addClass("s-selected"),
k=i);a.eventBus.trigger(e.selectionChange,{suggestion:k,isScrollIntoSearchBox:m,searchTerm:t,previousSearchTerm:u});s.val()!==""&&f.preventDefault()}d===13&&(d=q(),d.length>0&&(a.eventBus.trigger(e.suggestionClicked,{suggestion:d,searchTerm:t,previousSearchTerm:u}),f.preventDefault()))}}function o(d){d=d.keyCode;d===13?l(d):d===27?l(d):(t=b.getKeyword(s),t!==u&&i.indexOf(d)===-1&&(t===void 0||t===""?(l(),u=""):(a.eventBus.triggerThrottledEvent(e.suggestionsNeeded,t),u=t)))}function j(){setTimeout(function(){return function(){l();
a.eventBus.trigger(e.searchBoxFocusOut)}}(),300)}function m(){a.eventBus.trigger(e.searchBoxFocusIn)}function l(b){t=void 0;a.eventBus.trigger(e.hideDropdown,{keyCode:b})}function q(){return r.find(".s-suggestion.s-selected")}var v,r,s,t,u;(function(){if(f!==void 0){v=f.$form;r=f.$dropdown;s=f.$searchbox;var a="#"+s.attr("id");v.delegate(a,"focusin",m).delegate(a,"focusout",j).delegate(a,"keydown",g).delegate(a,"keyup",o);u=s.val()}})()}});window.$Nav.when("$","sx.iss.utils","NavDomApi","sx.iss.DomUtils",
"sx.iss.DebugUtils").build("sx.iss.SuggestionEventHandler",function(c,a,b,g,e){return function(b,i){i.delegate(".s-suggestion","click",function(d){var f=c(this);e.logDebug("Suggestion clicked",f);a.eventBus.trigger(b.suggestionClicked,{suggestion:f});d.preventDefault()}).delegate(".s-suggestion","mouseover",function(a){g.hoverOverEl(c(a.currentTarget))}).delegate(".s-suggestion","mouseout",function(a){g.hoverOutEl(c(a.currentTarget))})}});window.$Nav.when("$","sx.iss.utils","sx.iss.DebugUtils","sx.iss.DomUtils").build("sx.iss.CustomSearchBoxEventHandler",
function(c,a,b,g){return function(e,h,i){function d(a){k.hide();typeof i.manualOverride==="function"&&(a=i.manualOverride(a),a!==null&&a.length>0&&f(a));c(i.submitId).removeAttr("disabled")}function f(a){n.find(g.hiddenInputClass).remove();a=g.getFormParams(a);b.logDebug("Updating form with params.",a);n.attr("action",a.uri);for(var d="",a=a.formParams,f=0;f<a.length;f++){var e=a[f],c=decodeURIComponent(e.value);d+='<input type="hidden" class="'+g.hiddenInputValue+'" name="'+e.name+'" value="'+c+
'"/>'}n.append(d)}var n,k;n=e.$form;k=e.$dropdown;a.eventBus.listen(h.suggestionClicked,function(a){b.logDebug("Suggestion clicked",a);f(a.suggestion.data("url"));n.submit()});a.eventBus.listen(h.noSuggestions,function(a){d(a)});a.eventBus.listen(h.suggestionsReadyForDisplay,function(a){a.suggestions.length===2&&a.suggestions[1].type==="separator"&&a.suggestions[0].isExactMatch===!0?(a=k.find(g.suggestionClass).eq(0),f(a.data("url"))):a.searchTerm.length>=4?d(a.searchTerm):c(i.submitId).attr("disabled",
"disabled")});a.eventBus.listen(h.hideDropdown,function(){k.hide()})}});window.$Nav.when("sx.iss.utils","sx.iss.Events","sx.iss.TimingEvents","sx.iss.MetricsLogger").build("sx.iss.SuggestionAggregator",function(c,a,b,g){return function(e,h){function i(d){c.timingProvider.startTimer(b.latency.group,b.latency.events.timeToDisplay);g.startEndToEndLogging();if(!f[d]){f[d]={remainingProviders:e.length,searchTerm:d,suggestionSets:{}};for(var i=0;i<e.length;i++){var o=a.createEvent(e[i],h.suggestionsNeeded);
c.eventBus.trigger(o,d)}}}function d(a){var b=f[a.searchTerm],a=a.suggestionSets,d;for(d in a)a.hasOwnProperty(d)&&(b.suggestionSets[d]=a[d]);--b.remainingProviders||(delete f[b.searchTerm],c.eventBus.trigger(h.suggestionsReady,b))}var f={};(function(){for(var b=0;b<e.length;b++){var f=a.createEvent(e[b],h.suggestionsReady);c.eventBus.listen(f,d,this)}c.eventBus.listen(h.suggestionsNeeded,i,this)})()}});window.$Nav.when("$","sx.iss.utils","sx.iss.SuggestionTypes").build("sx.iss.SuggestionSequencer",
function(c,a,b){return function(c){var e=[b.department.name,b.a9Corpus.name,b.a9XOnly.name,b.a9Xcat.name,b.a9.name,"array"],h={type:"separator"};this.sequence=function(a){for(var b=a.suggestionSets,a=[],f=0,n=this.isDeepNode(c),k=0;k<e.length;k++){var o=b[e[k]];if(!(typeof o==="undefined"||o.length===0)){for(var j=0;j<o.length&&f<10;j++){var m=o[j];m.dispIdx=a.length;a.push(m);f++}f>0&&!n&&a.push(h)}}n&&(a=this.sequenceDeepNodeResults(a));b=a.length;b>0&&a[b-1].type==="separator"&&a.splice(-1,1);
return a};this.isDeepNode=function(b){var d,f;b.deepNodeISS&&(d=a.suggestionUtils.getDeepNodeAlias(b.deepNodeISS),f=a.suggestionUtils.getDeepNodeCategoryName(d,b.deepNodeISS));return d!==void 0&&f!==void 0};this.sequenceDeepNodeResults=function(a){for(var d,f,e=[],c=0;c<a.length;c++)f=a[c],(d===b.a9Xcat.name||d===b.a9XOnly.name)&&f.type===b.a9.name?e.unshift(f):e.push(f),d=f.type;return e}}});window.$Nav.when("$","sx.iss.utils","sx.iss.Events","NavDomApi").build("sx.iss.MetricsLogger",function(c,
a,b,g){function e(){var a=g.isSearchBoxFocused()?n:f;ue.tag(a)}function h(){uet(k,d,m);uet(o,d,m);uex(j,d,m)}function i(){return typeof uet==="function"&&typeof uex==="function"}var d="iss-init-pc",f="iss-on-time",n="iss-late",k="cf",o="be",j="ld",m={wb:1};i()&&(a.eventBus.listen(b.globals.initializeNavSearchBox,e),a.eventBus.listen(b.globals.issLoaded,h));return{startEndToEndLogging:function(){i()&&uet("bb","iss-end-to-end-a9",m)},stopEndToEndLogging:function(){i()&&(uet(k,"iss-end-to-end-a9",m),
uet(o,"iss-end-to-end-a9",m),uex(j,"iss-end-to-end-a9",m))}}});window.$Nav.when("$","sx.iss.utils","sx.iss.TimingEvents","sx.iss.SuggestionTypes","sx.iss.SearchBoxEventHandler","sx.iss.A9SuggestionProvider","sx.iss.DepartmentSuggestionProvider","sx.iss.SuggestionAggregator","sx.iss.SuggestionDisplayProvider","sx.iss.SuggestionSequencer","sx.iss.IssDisplayProvider","sx.iss.TemplateInstaller","sx.iss.SuggestionEventHandler","sx.iss.DesktopSearchBoxEventHandler","NavDomApi","sx.iss.Events","sx.iss.Reftag",
"sx.iss.Weblab","sx.iss.DebugUtils","sx.iss.MetricsLogger").build("sx.iss.IssParentCoordinator",function(c,a,b,g,e,h,i,d,f,n,k,o,j,m,l,q,v,r,s,t){return function(u){function C(a){var b={provider:new f(a.name,a.templateId)};return a===g.a9Xcat||a===g.a9XOnly?c.extend(b,{partials:[{key:"storeHtml",provider:new f(a.name,"s-storeText"),formatter:{string:u.deptText,toReplace:"{department}"}}]}):b.provider}var w,J,D=!1;s.isQIAEnabled()&&c.extend(u,{cf:1});J={$form:l.getForm(),$dropdown:l.getDropdown(),
$searchbox:l.getSearchBox()};w=q.createInstance();l.getForm().data("originalSearchTerm",l.getKeyword());l.getForm().data("originalAlias",l.getAliasFromDropdown());(function(){new e(u,J,w);o.init();var b=[(new h("desktop",u,w)).getName()],c=[C(g.a9),C(g.a9Corpus),new f("separator","s-separator"),C(g.a9Xcat),C(g.a9XOnly)];if(u.hasOwnProperty("isDigitalFeaturesEnabled")&&u.isDigitalFeaturesEnabled===1){c.push(new f(g.department.name,g.department.templateId));var s=new i(u,w);b.push(s.getName())}new k("suggestions-template",
new n(u),c,w,u);new d(b,w);a.eventBus.trigger(q.globals.initializeNavSearchBox);b=new m(w,u);new v(w,u,{shouldAddImeTag:b.getWasCompositionUsed});new j(w,l.getDropdown());new r(u,w)})();a.eventBus.listen(w.suggestionsReadyForDisplay,function(d){D&&(J.$searchbox.val().length===0?s.logDebug('Search term is empty, abort rendering for the search term "'+d.searchTerm+'"'):(l.showDropdown(d.display),a.timingProvider.stopTimer(b.latency.group,b.latency.events.timeToDisplay),t.stopEndToEndLogging(),a.eventBus.trigger(w.suggestionsRendered,
d),a.eventBus.trigger(q.globals.suggestionsRendered,d)))});a.eventBus.listen(w.hideDropdown,function(){D=!1});a.eventBus.listen(w.suggestionsNeeded,function(){D=!0})}});window.$Nav.when("$","sx.iss.utils","sx.iss.SearchBoxEventHandler","sx.iss.SuggestionAggregator","sx.iss.SuggestionDisplayProvider","sx.iss.SuggestionSequencer","sx.iss.IssDisplayProvider","sx.iss.TemplateInstaller","sx.iss.SuggestionEventHandler","sx.iss.Events","sx.iss.DomUtils","sx.iss.ArraySuggestionProvider","sx.iss.CustomSearchBoxEventHandler").build("sx.iss.CustomParentCoordinator",
function(c,a,b,g,e,h,i,d,f,n,k,o,j){return function(m){var l,q;(function(){d.init();l=n.createInstance();var a=m.searchboxId,r=c(m.formId),s=c('<div id="search-dropdown-custom" class="search-dropdown"></div>');r.after(s);q={$form:r,$dropdown:s,$searchbox:c(a)};q.$dropdown.css({width:q.$searchbox.outerWidth()});new b(m,q,l);new f(l,q.$dropdown);new j(q,l,m);m.hasOwnProperty("src")&&k.isArray(m.src)&&(a=new o(m.src,l),new g([a.name],l));a=[new e("array","s-minimal")];new i("suggestions-template",new h(m),
a,l,m)})();a.eventBus.listen(l.suggestionsReadyForDisplay,function(b){q.$dropdown.html(b.display);q.$dropdown.show();a.eventBus.trigger(l.suggestionsRendered,b)});return{dropdownId:"search-dropdown-custom"}}});window.$Nav.importEvent("jQuery",{as:"$",global:"jQuery"});window.$Nav.when("$","sx.iss.utils","sx.iss.Events","sx.iss.A9SuggestionProvider","sx.iss.DepartmentSuggestionProvider","sx.iss.A9SearchSuggestionEventHandler","sx.iss.HelpSuggestionProvider","sx.iss.RecentSearchSuggestionProvider",
"sx.iss.RecentSearchSuggestionEventHandler","sx.iss.SuggestionHighlightingProvider","sx.iss.SuggestionAggregator","sx.iss.SuggestionSequencer","sx.iss.SuggestionDisplayProvider","sx.iss.IssDisplayProvider","sx.iss.IssParentCoordinator","sx.iss.PublicApi","sx.iss.MetricsLogger","sx.iss.CustomParentCoordinator").build("sx.iss",function(c,a,b,g,e,h,i,d,f,n,k,o,j,m,l,q,v,r){g={Events:b,A9SuggestionProvider:g,DepartmentSuggestionProvider:e,A9SearchSuggestionEventHandler:h,HelpSuggestionProvider:i,RecentSearchSuggestionProvider:d,
RecentSearchSuggestionEventHandler:f,SuggestionHighlightingProvider:n,SuggestionAggregator:k,SuggestionSequencer:o,SuggestionDisplayProvider:j,IssDisplayProvider:m,IssParentCoordinator:l,CustomParentCoordinator:r,IssParentCoordinatorMobile:l,SuggestionSequencerMobile:o,isNewIss:!0};c.extend(g,g,q);a.eventBus.trigger(b.globals.issLoaded);return g});window.$Nav.when("sx.iss").run(function(c){window.$Nav.publish("sx.iss",c);window.$Nav.publish("search-js-autocomplete",c)})})})(function(){var A=window.AmazonUIPageJS||
P,j=A.attributeErrors;return j?j("RetailSearchAutocompleteAssets"):A}());
/* ******** */
(function(d){d.execute(function(){if(!window.$SearchJS&&window.$Nav)window.$SearchJS=$Nav.make("sx");window.$SearchJS&&($SearchJS.importEvent("jQuery",{as:"$",global:"jQuery"}),$SearchJS.importEvent("jQuery",{global:"jQuery"}),$SearchJS.when("jQuery").run("searchCSL-lib",function(c){c.searchCSL=c.searchCSL||new function(){var b=this,g=[],e=[],d,i,j,f,h=200,k;b.init=function(a,l,c){a&&l&&!d&&(d=a,b.updateRid(l),c&&(h=c))};b.updateRid=function(a){a&&i!=a&&(b.tx(),i=a,j={})};b.addWlt=function(a){if(a){if(a.call&&
(a=a(),!a))return;j[a]||(g.push(a),j[a]=1,b.scheduleTx())}};b.addAmabotPrerendered=function(a){a&&a.rid&&a.selections&&a.selections.length&&(e.push(a),b.scheduleTx())};b.scheduleTx=function(){if(h==0)b.tx();else{if(!k){var a=window.onbeforeunload;window.onbeforeunload=function(c){f&&(window.clearInterval(f),f=void 0);b.tx();k=!1;return a&&a.call?a(c):void 0};k=!0}!f&&h>0&&(f=window.setTimeout(function(){f=void 0;b.tx()},h))}};b.tx=function(){if(g.length||e.length){var a="/mn/search/csl?";g.length&&
(a+="rrid="+i+"&cpt="+d+"&ctw="+g.join("|"),g=[]);if(e.length){var b="";c.each(e,function(a,d){b+=d.rid+":";c.each(d.selections,function(a,c){c&&(b+=c+(a!=d.selections.length-1?",":""))});b+=a!=e.length-1?".":""});e=[];b&&(a+=a.charAt(a.length-1)=="?"?"":"&",a+="amabotSelections="+b)}(new Image).src=a}}};$SearchJS.publish("search-csl",c.searchCSL)}))})})(function(){var d=window.AmazonUIPageJS||P,c=d.attributeErrors;return c?c("RetailSearchClientSideLoggingAuiAssets"):d}());
/* ******** */
(function(c){c.execute(function(){(function(){c.register("p13n-sc-math",function(){return Math});c.register("p13n-sc-document",function(){return document});c.register("p13n-sc-window",function(){return window});c.register("p13n-sc-undefined",function(){});var b=function(){return window.P&&window.P.AUI_BUILD_DATE};b()?(c.when("jQuery").register("p13n-sc-jQuery",function(b){return b}),c.when("ready").register("p13n-sc-ready",function(){})):window.amznJQ&&(window.amznJQ.available("jQuery",function(){c.register("p13n-sc-jQuery",
function(){return window.amznJQ.jQuery})}),window.amznJQ.onReady("jQuery",function(){c.register("p13n-sc-ready",function(){})}),window.amznJQ.available("amazonShoveler",function(){c.register("p13n-sc-amznJQ-shoveler",function(){})}));c.when("p13n-sc-window").register("p13n-sc-util",function(f){var g=f.ueLogError;typeof g!=="function"&&(g=function(b,f){if(f&&f.message)throw Error(f.message);if(b&&b.message)throw Error(b.message);});var c=function(b,f){g({logLevel:b,attribution:"P13NSharedSitewideJS",
message:"[p13n-sc] "+f})};return{constants:{DATA_ATTR_P13N_FEATURE_NAME:"p13nFeatureName"},count:f.ue&&f.ue.count||function(){},isAUI:b,log:{warn:function(b){c("WARN",b)},error:function(b){c("ERROR",b)}}}})})();c.when("p13n-sc-jQuery","p13n-sc-window","p13n-sc-undefined").register("p13n-sc-heartbeat",function(b,f,c){var i=f.clearInterval,e={},k,l,a=function(){if(!k){var a=f.setInterval(function(){var b=a,f=(new Date).getTime();b!==k?i(b):((!l||f-l>200)&&j(),l=(new Date).getTime())},200);k=a}},j=function(){b.each(e,
function(a,b){b.call(f)})};return{subscribe:function(b,d){e[b]||(e[b]=d,a())},unsubscribe:function(a){e[a]&&delete e[a];var a=!0,b;for(b in e)e.hasOwnProperty(b)&&(a=!1);a&&(i(k),k=c)}}});c.when("p13n-sc-jQuery","p13n-sc-heartbeat").register("p13n-sc-call-on-visible",function(b,f){var c=[],i=b(window),e=function(){for(var b=i.scrollTop()+i.height(),e=i.scrollLeft()+i.width(),a=c.length-1;a>=0;a--){var j=c[a],h=j.callback,d=j.$element,o=j.distanceY,j=j.distanceX;if(d.parents("body").size()===0)c.splice(a,
1);else if(!d.is(":hidden")){var n=d.offset();b-o>n.top&&e-j>n.left&&(h.call(null,d[0]),c.splice(a,1))}}c.length===0&&f.unsubscribe("p13n-sc-call-on-visible")};return{register:function(k,i,a){var j=a&&typeof a.distance!=="undefined"?a.distance:0,h=a&&typeof a.distanceY!=="undefined"?a.distanceY:j,d=a&&typeof a.distanceX!=="undefined"?a.distanceX:0;b(k).each(function(){c.push({$element:b(this),callback:i,distanceY:h,distanceX:d})});f.subscribe("p13n-sc-call-on-visible",e);e()}}});c.when("A","jQuery",
"p13n-sc-call-on-visible","p13n-sc-util","p13n-sc-math").register("p13n-sc-view-trigger",function(b,f,g,i,e){var k=function(a){var c=f(a),a=c.attr("data-params"),h=c.attr("data-url");if(a&&h){var a=b.parseJSON(a),d=c.offset(),c=[d.top,d.left,c.height(),f(window).width()];a.elementRect=c.join(",");var g=0,k={cache:!0,crossDomain:!1,data:f.param(a,!1),error:function(a){a=a.status||0;g>=3||a>=400&&a<500||setTimeout(i,200*e.pow(2,g))},global:!1,url:h},i=function(){g+=1;f.ajax(k)};i()}},l=function(a){var e=
f(a);if(e.size()===1){var h=e.attr("data-params"),h=h?b.parseJSON(h):{};if(!(h.allowEmpty!==!0&&e.text().trim().length===0)){var d=e.height();if(!(h.allowEmpty!==!0&&d<5)){d=0;if(typeof h.distance==="number")d=h.distance;e.attr("data-p13n-sc-vt-initialized")||(e.attr("data-p13n-sc-vt-initialized",!0),g.register(a,function(){k(a)},{distance:d}))}}}},i=function(){b.each(f(".p13n-sc-vt:not([data-p13n-sc-vt-initialized])"),function(a){l(a)})};c.execute(i);c.when("afterReady").execute("p13n-sc-view-trigger:init",
i);return{initializeElement:l}});c.when("p13n-sc-jQuery","p13n-sc-util","p13n-sc-window","p13n-sc-document","p13n-sc-ready").register("p13n-sc-logger",function(b,f,c,i){function e(a){return a.join("")}function k(a,b){var d=a.attr(b),h={};d!==void 0&&d!==null&&(h=typeof c.JSON!=="undefined"?JSON.parse(d):eval("("+d+")"));return h}function l(a,d){for(var h=[a.widget,":"],f=0;f<a.asins.length;f++){var c=a.asins[f];h.push(c.asin,"@");b.each(c,function(a,b){a!=="asin"&&h.push(a,"=",b,"|")});h.splice(h.length-
1,1);h.push(",")}a.asins.length>0&&h.splice(h.length-1,1);d&&(h.push(":","action=",a.action),b.each(a.meta,function(a,b){h.push(",",a,"=",b)}));return e(h)}function a(a,d){var h=k(b(d),"data-p13n-asin-metadata");if(h&&h.asin){var f=h.asin,e=k(b(a),"data-p13n-asin-metadata");e&&b.extend(!0,h,e[f]);return h}}function j(a,h){var j=new Image;f.count("p13n:logger:attempt",1);j.onerror=function(){d++;f.count("p13n:logger:error",1)};j.src=e(["https:"===i.location.protocol?"https://":"http://",c.ue_furl||
"fls-na.amazon.com","/1/","p13n-shared-components","/1/OP/p13n/",h,e(["?",b.param(k(b(a.featureElement),"data-p13n-global"))])])}function h(){return d>3?(o||(f.log.warn("impression image load failed too many times, no longer logging impressions"),f.count("p13n:logger:abort",1),o=!0),!0):!1}var d=0,o=!1,n={},p={},q={logAction:function(d){if(!h())if("featureElement"in d)if("action"in d){var c=b(d.featureElement);d.asins=b.map(b(d.featureElement).find(".p13n-asin").filter(":visible"),function(b){return a(c,
b)});d.meta=d.meta||{};var g=k(c,"data-p13n-feature-metadata");b.extend(!0,d.meta,g);d.widget=c.attr("data-p13n-feature-name");d.widget in n||(n[d.widget]={});for(var i=g=0;i<d.asins.length;i++)d.asins[i].asin in n[d.widget]||(n[d.widget][d.asins[i].asin]=!0,g++);d.logOnlyOnNew&&g===0||(g=e(["action/",e([d.widget,"_:",d.action,"@v=",d.eventtime||0,",impressed@v=",g]),"/",l(d,!0)]),d.replicateAsinImpressions&&(i=e(["asin/",l(d,!1)]),g=e(["batch/",g,"$",i])),j(d,g))}else f.log.warn("action missing in eventData for logAction");
else f.log.warn("featureElement missing in eventData for logAction")},logAsyncAction:function(a){var d=(new Date).getTime(),h=typeof a.initialDelay==="number"?a.initialDelay:400,f=typeof a.timeout==="number"?a.timeout:5E3,e=b(a.featureElement);a.widget=e.attr("data-p13n-feature-name");a.widget in p&&c.clearTimeout(p[a.widget]);var j=function(){var b=a.isEventComplete(),h=(new Date).getTime();if(h-d<f&&!b)p[a.widget]=c.setTimeout(j,150);else{if(!b){if(!("meta"in a))a.meta={};a.meta.err="notfinished"}a.eventtime=
h-d;delete p[a.widget];q.logAction(a)}};p[a.widget]=c.setTimeout(j,h)},eventPending:function(a){return b(a).attr("data-p13n-feature-name")in p},impressAsin:function(d){if(!h())if("featureElement"in d)if("faceoutElement"in d){var c=b(d.faceoutElement),g=b(d.featureElement);d.widget=g.attr("data-p13n-feature-name");d.asins=[a(g,c)];c=e(["asin/",l(d,!1)]);j(d,c)}else f.log.warn("faceoutElement missing in eventData for logAction");else f.log.warn("featureElement missing in eventData for logAction")}};
return q});c.when("jQuery","A","p13n-sc-call-on-visible","p13n-sc-logger","ready").register("p13n-sc-faceout-logger",function(b,f,c,i){var e=function(f,e){var a=b(f),j=b(e);a.length===1&&!a.attr("data-p13n-sc-fl-initialized")&&(a.attr("data-p13n-sc-fl-initialized",!0),c.register(a,function(){i.impressAsin({featureElement:j,faceoutElement:a})}))};f.on("p13n:faceoutsloaded",function(f){b(f).find(".p13n-asin:not([data-p13n-sc-fl-initialized])").each(function(b,a){e(a,f)})})});c.when("A","jQuery").register("p13n-sc-lazy-image-loader",
function(b,f){return{loadImages:function(c){b.executeDeferred();c.find(".p13n-sc-lazy-loaded-img").each(function(c,e){var g=f(e),l=g.find(".a-dynamic-image");l.load(function(){g.removeClass("p13n-sc-lazy-loaded-img")});b.loadDynamicImage(l)})}}});c.when("p13n-sc-jQuery","p13n-sc-util","p13n-sc-math","p13n-sc-line-truncator-settings").register("p13n-sc-line-truncator",function(b,f,c,i){function e(a){this.$element=a;this.$experimentElement=b("<div>").addClass("p13n-sc-offscreen-truncate");this.maxRows=
a.attr("data-rows");this.lineHeight=i.lineHeight;this.maxRows||f.log.error("Truncation element missing necessary line number data")}var k=/(?=[ \-\/])/,l=/[^\/\-\[\]():\s]/;e.prototype.truncate=function(){var a=this.$element.html(),a=a.trim();this.$element.append(this.$experimentElement);if(!this.checkLineFit(a)){var b=this.truncateByToken(a);b?(this.$element.html(b),this.$element.attr({title:a})):f.log.error("Unable to successfully truncate line "+a)}this.$experimentElement.remove()};e.prototype.checkLineFit=
function(a){this.$experimentElement.html(a);a=this.$experimentElement.get(0).clientHeight/this.lineHeight;return c.round(a)<=this.maxRows};e.prototype.truncateByToken=function(a){for(var a=a.split(this.getTokenSeparatorRegex()),b=1,h=a.length,d,f,e=0;b!==h;)if(d=c.floor((h+b)/2),f=a.slice(0,d).join("")+"&hellip;",this.checkLineFit(f)){if(h-d<=1){for(e=d;e>0&&!l.test(a[e-1]);)e--;break}b=d}else h=d;return e===0?void 0:a.slice(0,e).join("")+"&hellip;"};e.prototype.getTokenSeparatorRegex=function(){return this.$element.attr("data-truncate-by-character")?
"":k};return{truncateLines:function(a){a.find(".p13n-sc-truncate").each(function(){var a=new e(b(this));a&&(a.truncate(),b(this).addClass("p13n-sc-truncated").removeClass("p13n-sc-truncate"))})}}});c.register("p13n-sc-line-truncator-settings",function(){return{lineHeight:19}});c.when("A","jQuery","a-carousel-framework","p13n-sc-call-on-visible","p13n-sc-logger","p13n-sc-util","ready").execute("p13n-sc-carousel-logger",function(b,f,c,i,e,k){function l(a,b){var c=a.getAttr("pageNumber"),g=a.dom.$container;
g.data("p13nPreviousPage",c);e.logAsyncAction(f.extend(!0,{},{featureElement:g,isEventComplete:function(){return g.find(".a-carousel-card-empty").size()===0&&!a.getAttr("animating")},meta:{p:c},replicateAsinImpressions:!0},b))}function a(a){j(a)&&i.register(a.dom.$container,function(){l(a,{action:"view"})})}var j=function(a){return typeof a==="undefined"?!1:a.dom.$container.data(k.constants.DATA_ATTR_P13N_FEATURE_NAME)?!0:!1};b.each(c.getAllCarousels(),function(b){b.dom.$container.hasClass("a-carousel-initialized")&&
a(b)});b.on("a:carousel:init",function(b){a(b.carousel)});f(document).delegate(".a-carousel-container[data-p13n-feature-name] .a-carousel-goto-nextpage","click",function(a){a=c.getCarousel(a.target);l(a,{action:"shovel_right"})});f(document).delegate(".a-carousel-container[data-p13n-feature-name] .a-carousel-goto-prevpage","click",function(a){a=c.getCarousel(a.target);l(a,{action:"shovel_left"})});f(document).delegate(".a-carousel-container[data-p13n-feature-name] .a-carousel-restart","click",function(a){a=
c.getCarousel(a.target);l(a,{action:"start_over",meta:{op:a.dom.$container.data("p13nPreviousPage")}})});b.on("a:carousel:change:pageSize",function(a){a=a.carousel;j(a)&&a.dom.$container.hasClass("a-carousel-initialized")&&l(a,{action:"resize",logOnlyOnNew:!0})})});c.when("p13n-sc-jQuery","p13n-sc-window","p13n-sc-document","p13n-sc-call-on-visible","p13n-sc-logger","p13n-sc-util","p13n-sc-amznJQ-shoveler").register("p13n-sc-non-aui-carousel",function(b,f,g,i,e,k){var l=function(a){k.count("p13n-sc-non-aui-carousel:init",
1);var d=a.attr("data-widgetname"),c=b("#"+d+"Data");if(c.length!==1)return!1;if(a.attr("data-p13n-sc-carousel-initialized"))return!1;else a.attr("data-p13n-sc-carousel-initialized",!0);var g=c.text().split(","),j=a.find(".shoveler-content > ul"),i="input#"+d+"ShvlState",m=function(){},l=200,u=!1,w=function(){var d=l;a.find(".p13nimp, .p13n-asin").each(function(){var a=b(this).outerHeight(!0);a>d&&(d=a)});d>l&&(l=d,j.animate({height:d},200,"linear"));u||x()},x=function(){var b=l/2;a.find("a.next-button, a.back-button").css("top",
b);u=!0},r=a.find(".shoveler").shoveler(function(a,d){var e="",e=typeof f.JSON!=="undefined"?JSON.parse(c.attr("data-ajax")):eval("("+c.attr("data-ajax")+")");e.asins=g.slice(a,a+d).join(",");e.count=d;e.offset=a;e=b.param(e);return c.attr("data-url")+"?"+e},g.length,{cellTransformer:function(a){return a===null?"":a},cellChangeSpeedInMs:30,preloadNextPage:!0,prevButtonSelector:"a.back-button",nextButtonSelector:"a.next-button",startOverSelector:"span.start-over",startOverLinkSelector:"a",horizPadding:14,
state:{ready:function(){return b(i).val().length>0},get:function(){return parseInt(b(i).val(),10)},set:function(a){b(i).val(a)}},onUpdateUIHandler:function(){w();m()}}),v=0,y=function(){var a=b(f).width();v!==a&&(r.updateUI(),v=a)},t=null;a.resize(function(){t&&f.clearTimeout(t);t=f.setTimeout(y,100)});var s=function(d){e.logAsyncAction(b.extend(!0,{},{featureElement:a,isEventComplete:function(){return a.find("li.shoveler-cell.shoveler-progress").size()===0},replicateAsinImpressions:!0},d))};s({action:"view",
meta:{p:r.getCurrentPage()+1}});a.find(".back-button").click(function(){s({action:"shovel_left",meta:{p:r.getCurrentPage()+1}})});a.find(".next-button").click(function(){s({action:"shovel_right",meta:{p:r.getCurrentPage()+1}})});a.find(".start-over-link").mousedown(function(){s({action:"start_over",meta:{p:1,op:r.getCurrentPage()+1}})});m=function(){e.eventPending(a)||s({action:"resize",page:r.getCurrentPage()+1,logOnlyOnNew:!0,initialDelay:2E3})}},a=function(a){var d={distanceY:-250,distanceX:0};
b(a).find(".p13n-sc-nonAUI-carousel").andSelf().filter(".p13n-sc-nonAUI-carousel").each(function(a,e){i.register(e,function(){l(b(e))},d)})},j=function(){a(g)};j();c.when("p13n-sc-ready").execute("p13n-sc-non-aui-carousel:readyInit",j);return{init:a}});c.when("p13n-sc-jQuery","p13n-sc-util").execute("p13n-sc-carousel-initialization-setup",function(b,f){f.isAUI()?c.when("a-carousel-framework").register("p13n-sc-carousel-init",function(b){return{init:function(){b.createAll()}}}):c.when("p13n-sc-non-aui-carousel").register("p13n-sc-carousel-init",
function(b){return{init:function(c){b.init(c)}}})})})})(function(){var c=window.AmazonUIPageJS||P,b=c.attributeErrors;return b?b("P13NSharedSitewideJS"):c}());
/* ******** */
